# fly.toml app configuration file generated for eclecticelectronics on 2026-01-07T18:23:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eclecticelectronics'
primary_region = 'ord'

[build]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[processes]
app = "gunicorn app:app --bind 0.0.0.0:8080"

[http_service]
    internal_port = 8080
    force_https = true

    auto_start_machines = true
    auto_stop_machines = true
    min_machines_running = 0
    processes = ["app"]
[mounts]
    source = "site_state"
    destination = "/persist"
